#!/usr/bin/env zsh
#
#  Copyright (c) 2022 AlertAvert.com.  All rights reserved.
#  Author: Marco Massenzio (marco@alertavert.com)
#
# Usage: get-version
# Extracts version from build.settings


set -eu
workdir=$(dirname $0)

# It's ugly, I know - doing it using bash regex is even worse.
version=$(cat ${workdir}/build.settings| grep "^version" | cut -f 2 -d "=" | sed "s/'//g" | sed "s/ //g")

echo $version
